version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    container_name: zookeeper
    env_file:
      - .env
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=${KAFKA_USERNAME}
      - ZOO_SERVER_PASSWORDS=${KAFKA_PASSWORD}
      - ZOO_CLIENT_USER=${KAFKA_USERNAME}
      - ZOO_CLIENT_PASSWORD=${KAFKA_PASSWORD}
    ports:
      - "2181:2181"
    networks:
      - kafkanet
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  kafka-0:
    image: bitnami/kafka:2.8.1
    container_name: kafka-0
    depends_on:
      - zookeeper
    env_file:
      - .env
    networks:
      - kafkanet
    ports:
      - "9092:9092" # External access via SASL_PLAINTEXT
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      
      # Define os protocolos de segurança para os listeners
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      
      # Define os listeners internos e externos
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka-0:29092,EXTERNAL://0.0.0.0:9092
      
      # Define os listeners que serão anunciados externamente
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-0:29092,EXTERNAL://${KAFKA_HOST}:9092
      
      # Define o listener que será usado para comunicação entre brokers
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      
      - KAFKA_CFG_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_OPTS=-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf
      
      - ALLOW_PLAINTEXT_LISTENER=no
      
      # Client credentials
      - KAFKA_CLIENT_USERS=${KAFKA_USERNAME}
      - KAFKA_CLIENT_PASSWORDS=${KAFKA_PASSWORD}
      
      # Interbroker credentials
      - KAFKA_INTER_BROKER_USER=${KAFKA_USERNAME}
      - KAFKA_INTER_BROKER_PASSWORD=${KAFKA_PASSWORD}
      
      # Zookeeper credentials
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=${KAFKA_USERNAME}
      - KAFKA_ZOOKEEPER_PASSWORD=${KAFKA_PASSWORD}
    volumes:
      - kafka_data_0:/bitnami/kafka
      - ./certs/kafka_server_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    depends_on:
      - kafka-0
    networks:
      - kafkanet
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-cluster-0
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-0:29092
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
    volumes:
      - kafka_data_0:/opt/kafka-ui/certs

volumes:
  zookeeper_data:
    driver: local
  kafka_data_0:
    driver: local

networks:
  kafkanet:
    name: kafka-network
